# Autogenerated constants for WSSK service
from enum import IntEnum
from jacdac.constants import *
JD_SERVICE_CLASS_WSSK = const(0x13b739fe)


class WsskStreamingType(IntEnum):
    JACDAC = const(0x1)
    DMESG = const(0x2)
    EXCEPTIONS = const(0x100)
    TEMPORARY_MASK = const(0xff)
    PERMAMENT_MASK = const(0xff00)
    DEFAULT_MASK = const(0x100)


class WsskDataType(IntEnum):
    BINARY = const(0x1)
    JSON = const(0x2)


JD_WSSK_CMD_ERROR = const(0xff)
JD_WSSK_CMD_SET_STREAMING = const(0x90)
JD_WSSK_CMD_PING_DEVICE = const(0x91)
JD_WSSK_CMD_PING_CLOUD = const(0x92)
JD_WSSK_CMD_GET_HASH = const(0x93)
JD_WSSK_CMD_DEPLOY_START = const(0x94)
JD_WSSK_CMD_DEPLOY_WRITE = const(0x95)
JD_WSSK_CMD_DEPLOY_FINISH = const(0x96)
JD_WSSK_CMD_C2D = const(0x97)
JD_WSSK_CMD_D2C = const(0x98)
JD_WSSK_CMD_JACDAC_PACKET = const(0x99)
JD_WSSK_CMD_DMESG = const(0x9a)
JD_WSSK_CMD_EXCEPTION_REPORT = const(0x9b)
JD_WSSK_PACK_FORMATS = {
    JD_WSSK_CMD_ERROR: "s",
    JD_WSSK_CMD_SET_STREAMING: "u16",
    JD_WSSK_CMD_PING_DEVICE: "b",
    JD_WSSK_CMD_PING_CLOUD: "b",
    JD_WSSK_CMD_DEPLOY_START: "u32",
    JD_WSSK_CMD_DEPLOY_WRITE: "b",
    JD_WSSK_CMD_C2D: "u8 z b",
    JD_WSSK_CMD_D2C: "u8 z b",
    JD_WSSK_CMD_JACDAC_PACKET: "b",
    JD_WSSK_CMD_DMESG: "b",
    JD_WSSK_CMD_EXCEPTION_REPORT: "b"
}
