# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class FlexClient(Client):
    """
    A bending or deflection sensor.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_FLEX, JD_FLEX_PACK_FORMATS, role)
    

    @property
    def bending(self) -> Optional[float]:
        """
        The relative position of the slider., /
        """
        reg = self.register(JD_FLEX_REG_BENDING)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def variant(self) -> Optional[FlexVariant]:
        """
        (Optional) Specifies the physical layout of the flex sensor.
        """
        reg = self.register(JD_FLEX_REG_VARIANT)
        value = reg.value(0)
        return cast(Optional[FlexVariant], value)

    
