# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class FlexClient(Client):
    """
    A bending or deflection sensor.
    Implements a client for the `Flex <https://microsoft.github.io/jacdac-docs/services/flex>`_ service.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_FLEX, JD_FLEX_PACK_FORMATS, role)
    

    @property
    def bending(self) -> Optional[float]:
        """
        The relative position of the slider., _: /
        """
        reg = self.register(JD_FLEX_REG_BENDING)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def variant(self) -> Optional[FlexVariant]:
        """
        (Optional) Specifies the physical layout of the flex sensor., 
        """
        reg = self.register(JD_FLEX_REG_VARIANT)
        values = reg.values()
        return cast(Optional[FlexVariant], values[0] if values else None)

    
