# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class MagnetometerClient(Client):
    """
    A 3-axis magnetometer.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_MAGNETOMETER, JD_MAGNETOMETER_PACK_FORMATS, role)
    

    @property
    def forces(self) -> Optional[tuple[int, int, int]]:
        """
        Indicates the current magnetic field on magnetometer.
        For reference: `1 mgauss` is `100 nT` (and `1 gauss` is `100 000 nT`)., x: nT,y: nT,z: nT
        """
        reg = self.register(JD_MAGNETOMETER_REG_FORCES)
        values = reg.values()
        return cast(Optional[tuple[int, int, int]], values)

    @property
    def forces_error(self) -> Optional[int]:
        """
        (Optional) Error on the readings., _: nT
        """
        reg = self.register(JD_MAGNETOMETER_REG_FORCES_ERROR)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)


    def calibrate(self, ) -> None:
        """
        Forces a calibration sequence where the user/device
        might have to rotate to be calibrated.
        """
        self.send_cmd_packed(JD_MAGNETOMETER_CMD_CALIBRATE, )
    
