# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional


class BridgeClient(Client):
    """
    Indicates that the device acts as a bridge to the Jacdac bus.
    Implements a client for the `Bridge <https://microsoft.github.io/jacdac-docs/services/bridge>`_ service.

    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_BRIDGE, JD_BRIDGE_PACK_FORMATS, role)


    @property
    def enabled(self) -> Optional[bool]:
        """
        Enables or disables the bridge., 
        """
        return self.register(JD_BRIDGE_REG_ENABLED).bool_value()

    @enabled.setter
    def enabled(self, value: bool) -> None:
        self.register(JD_BRIDGE_REG_ENABLED).set_values(value)


    
