# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class ThermometerClient(Client):
    """
    A thermometer measuring outside or inside environment.
    Implements a client for the `Thermometer <https://microsoft.github.io/jacdac-docs/services/thermometer>`_ service.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_THERMOMETER, JD_THERMOMETER_PACK_FORMATS, role)
    

    @property
    def temperature(self) -> Optional[float]:
        """
        The temperature., _: °C
        """
        reg = self.register(JD_THERMOMETER_REG_TEMPERATURE)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def min_temperature(self) -> Optional[float]:
        """
        Lowest temperature that can be reported., _: °C
        """
        reg = self.register(JD_THERMOMETER_REG_MIN_TEMPERATURE)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def max_temperature(self) -> Optional[float]:
        """
        Highest temperature that can be reported., _: °C
        """
        reg = self.register(JD_THERMOMETER_REG_MAX_TEMPERATURE)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def temperature_error(self) -> Optional[float]:
        """
        The real temperature is between `temperature - temperature_error` and `temperature + temperature_error`., _: °C
        """
        reg = self.register(JD_THERMOMETER_REG_TEMPERATURE_ERROR)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def variant(self) -> Optional[ThermometerVariant]:
        """
        (Optional) Specifies the type of thermometer., 
        """
        reg = self.register(JD_THERMOMETER_REG_VARIANT)
        values = reg.values()
        return cast(Optional[ThermometerVariant], values[0] if values else None)

    
