# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class RoverClient(Client):
    """
    A roving robot.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_ROVER, JD_ROVER_PACK_FORMATS, role)
    

    @property
    def kinematics(self) -> Optional[tuple[float, float, float, float, float]]:
        """
        The current position and orientation of the robot., x: cm,y: cm,vx: cm/s,vy: cm/s,heading: °
        """
        reg = self.register(JD_ROVER_REG_KINEMATICS)
        values = reg.values()
        return cast(Optional[tuple[float, float, float, float, float]], values)

    
