# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class RoverClient(Client):
    """
    A roving robot.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_ROVER, JD_ROVER_PACK_FORMATS, role)
    

    @property
    def x(self) -> Optional[float]:
        """
        The current position and orientation of the robot., cm
        """
        reg = self.register(JD_ROVER_REG_KINEMATICS)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def y(self) -> Optional[float]:
        """
        The current position and orientation of the robot., cm
        """
        reg = self.register(JD_ROVER_REG_KINEMATICS)
        value = reg.value(1)
        return cast(Optional[float], value)

    @property
    def vx(self) -> Optional[float]:
        """
        The current position and orientation of the robot., cm/s
        """
        reg = self.register(JD_ROVER_REG_KINEMATICS)
        value = reg.value(2)
        return cast(Optional[float], value)

    @property
    def vy(self) -> Optional[float]:
        """
        The current position and orientation of the robot., cm/s
        """
        reg = self.register(JD_ROVER_REG_KINEMATICS)
        value = reg.value(3)
        return cast(Optional[float], value)

    @property
    def heading(self) -> Optional[float]:
        """
        The current position and orientation of the robot., °
        """
        reg = self.register(JD_ROVER_REG_KINEMATICS)
        value = reg.value(4)
        return cast(Optional[float], value)

    
