# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class ServoClient(Client):
    """
    Servo is a small motor with arm that can be pointing at a specific direction.
     * 
     * The `min/max_angle/pulse` may be read-only if the servo is permanently affixed to its Jacdac controller.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_SERVO, JD_SERVO_PACK_FORMATS, role)
    

    @property
    def angle(self) -> Optional[float]:
        """
        Specifies the angle of the arm (request)., _: °
        """
        reg = self.register(JD_SERVO_REG_ANGLE)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @angle.setter
    def angle(self, value: float) -> None:
        self.enabled = True
        reg = self.register(JD_SERVO_REG_ANGLE)
        reg.set_values(value) # type: ignore


    @property
    def enabled(self) -> Optional[bool]:
        """
        Turn the power to the servo on/off., 
        """
        reg = self.register(JD_SERVO_REG_ENABLED)
        values = reg.values()
        return cast(Optional[bool], values[0] if values else None)

    @enabled.setter
    def enabled(self, value: bool) -> None:
        reg = self.register(JD_SERVO_REG_ENABLED)
        reg.set_values(value) # type: ignore


    @property
    def offset(self) -> Optional[float]:
        """
        Correction applied to the angle to account for the servo arm drift., _: °
        """
        reg = self.register(JD_SERVO_REG_OFFSET)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @offset.setter
    def offset(self, value: float) -> None:
        reg = self.register(JD_SERVO_REG_OFFSET)
        reg.set_values(value) # type: ignore


    @property
    def min_angle(self) -> Optional[float]:
        """
        Lowest angle that can be set., _: °
        """
        reg = self.register(JD_SERVO_REG_MIN_ANGLE)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def min_pulse(self) -> Optional[int]:
        """
        The length of pulse corresponding to lowest angle., _: us
        """
        reg = self.register(JD_SERVO_REG_MIN_PULSE)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    @min_pulse.setter
    def min_pulse(self, value: int) -> None:
        reg = self.register(JD_SERVO_REG_MIN_PULSE)
        reg.set_values(value) # type: ignore


    @property
    def max_angle(self) -> Optional[float]:
        """
        Highest angle that can be set., _: °
        """
        reg = self.register(JD_SERVO_REG_MAX_ANGLE)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def max_pulse(self) -> Optional[int]:
        """
        The length of pulse corresponding to highest angle., _: us
        """
        reg = self.register(JD_SERVO_REG_MAX_PULSE)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    @max_pulse.setter
    def max_pulse(self, value: int) -> None:
        reg = self.register(JD_SERVO_REG_MAX_PULSE)
        reg.set_values(value) # type: ignore


    @property
    def stall_torque(self) -> Optional[float]:
        """
        (Optional) The servo motor will stop rotating when it is trying to move a ``stall_torque`` weight at a radial distance of ``1.0`` cm., _: kg/cm
        """
        reg = self.register(JD_SERVO_REG_STALL_TORQUE)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def response_speed(self) -> Optional[float]:
        """
        (Optional) Time to move 60°., _: s/60°
        """
        reg = self.register(JD_SERVO_REG_RESPONSE_SPEED)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def current_angle(self) -> Optional[float]:
        """
        (Optional) The current physical position of the arm., _: °
        """
        reg = self.register(JD_SERVO_REG_CURRENT_ANGLE)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    
