# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class DotMatrixClient(Client):
    """
    A rectangular dot matrix display, made of monochrome LEDs or Braille pins.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_DOT_MATRIX, JD_DOT_MATRIX_PACK_FORMATS, role)
    

    @property
    def dots(self) -> Optional[bytes]:
        """
        The state of the screen where dot on/off state is
        stored as a bit, column by column. The column should be byte aligned.
        """
        reg = self.register(JD_DOT_MATRIX_REG_DOTS)
        value = reg.value(0)
        return cast(Optional[bytes], value)

    @dots.setter
    def dots(self, value: bytes) -> None:
        reg = self.register(JD_DOT_MATRIX_REG_DOTS)
        reg.set_value(0, value)


    @property
    def brightness(self) -> Optional[float]:
        """
        (Optional) Reads the general brightness of the display, brightness for LEDs. `0` when the screen is off., /
        """
        reg = self.register(JD_DOT_MATRIX_REG_BRIGHTNESS)
        value = reg.value(0)
        return cast(Optional[float], value)

    @brightness.setter
    def brightness(self, value: float) -> None:
        reg = self.register(JD_DOT_MATRIX_REG_BRIGHTNESS)
        reg.set_value(0, value)


    @property
    def rows(self) -> Optional[int]:
        """
        Number of rows on the screen, #
        """
        reg = self.register(JD_DOT_MATRIX_REG_ROWS)
        value = reg.value(0)
        return cast(Optional[int], value)

    @property
    def columns(self) -> Optional[int]:
        """
        Number of columns on the screen, #
        """
        reg = self.register(JD_DOT_MATRIX_REG_COLUMNS)
        value = reg.value(0)
        return cast(Optional[int], value)

    @property
    def variant(self) -> Optional[DotMatrixVariant]:
        """
        (Optional) Describes the type of matrix used.
        """
        reg = self.register(JD_DOT_MATRIX_REG_VARIANT)
        value = reg.value(0)
        return cast(Optional[DotMatrixVariant], value)

    
