# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class PressureButtonClient(Client):
    """
    A pressure sensitive push-button.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_PRESSURE_BUTTON, JD_PRESSURE_BUTTON_PACK_FORMATS, role)
    

    @property
    def threshold(self) -> Optional[float]:
        """
        Indicates the threshold for ``up`` events., /
        """
        reg = self.register(JD_PRESSURE_BUTTON_REG_THRESHOLD)
        value = reg.value(0)
        return cast(Optional[float], value)

    @threshold.setter
    def threshold(self, value: float) -> None:
        reg = self.register(JD_PRESSURE_BUTTON_REG_THRESHOLD)
        reg.set_value(0, value)


    
