# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class CompassClient(Client):
    """
    A sensor that measures the heading.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_COMPASS, JD_COMPASS_PACK_FORMATS, role)
    

    @property
    def heading(self) -> Optional[float]:
        """
        The heading with respect to the magnetic north., _: °
        """
        reg = self.register(JD_COMPASS_REG_HEADING)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def enabled(self) -> Optional[bool]:
        """
        Turn on or off the sensor. Turning on the sensor may start a calibration sequence., 
        """
        reg = self.register(JD_COMPASS_REG_ENABLED)
        values = reg.values()
        return cast(Optional[bool], values[0] if values else None)

    @enabled.setter
    def enabled(self, value: bool) -> None:
        reg = self.register(JD_COMPASS_REG_ENABLED)
        reg.set_values(value)


    @property
    def heading_error(self) -> Optional[float]:
        """
        (Optional) Error on the heading reading, _: °
        """
        reg = self.register(JD_COMPASS_REG_HEADING_ERROR)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)


    def calibrate(self, ) -> None:
        """
        Starts a calibration sequence for the compass.
        """
        self.send_cmd_packed(JD_COMPASS_CMD_CALIBRATE, )
    
