# Autogenerated constants for ROS service
from jacdac.constants import *
JD_SERVICE_CLASS_ROS = const(0x1524f42c)
JD_ROS_CMD_PUBLISH_MESSAGE = const(0x81)
JD_ROS_CMD_SUBSCRIBE_MESSAGE = const(0x82)
JD_ROS_CMD_MESSAGE = const(0x83)
JD_ROS_PACK_FORMATS = {
    JD_ROS_CMD_PUBLISH_MESSAGE: "z z s",
    JD_ROS_CMD_SUBSCRIBE_MESSAGE: "z s",
    JD_ROS_CMD_MESSAGE: "z z s"
}
