# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast
from jacdac.events import EventHandlerFn, UnsubscribeFn

class SoundLevelClient(Client):
    """
    A sound level detector sensor, gives a relative indication of the sound level.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_SOUND_LEVEL, JD_SOUND_LEVEL_PACK_FORMATS, role)
    

    @property
    def sound_level(self) -> Optional[float]:
        """
        The sound level detected by the microphone, /
        """
        reg = self.register(JD_SOUND_LEVEL_REG_SOUND_LEVEL)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def enabled(self) -> Optional[bool]:
        """
        Turn on or off the microphone.
        """
        reg = self.register(JD_SOUND_LEVEL_REG_ENABLED)
        value = reg.value(0)
        return cast(Optional[bool], value)

    @enabled.setter
    def enabled(self, value: bool) -> None:
        reg = self.register(JD_SOUND_LEVEL_REG_ENABLED)
        reg.set_value(0, value)


    @property
    def min_decibels(self) -> Optional[int]:
        """
        (Optional) The minimum power value considered by the sensor.
        If both ``min_decibels`` and ``max_decibels`` are supported,
        the volume in deciment can be linearly interpolated between
        ``[min_decibels, max_decibels]``., dB
        """
        reg = self.register(JD_SOUND_LEVEL_REG_MIN_DECIBELS)
        value = reg.value(0)
        return cast(Optional[int], value)

    @min_decibels.setter
    def min_decibels(self, value: int) -> None:
        reg = self.register(JD_SOUND_LEVEL_REG_MIN_DECIBELS)
        reg.set_value(0, value)


    @property
    def max_decibels(self) -> Optional[int]:
        """
        (Optional) The maximum power value considered by the sensor.
        If both ``min_decibels`` and ``max_decibels`` are supported,
        the volume in deciment can be linearly interpolated between
        ``[min_decibels, max_decibels]``., dB
        """
        reg = self.register(JD_SOUND_LEVEL_REG_MAX_DECIBELS)
        value = reg.value(0)
        return cast(Optional[int], value)

    @max_decibels.setter
    def max_decibels(self, value: int) -> None:
        reg = self.register(JD_SOUND_LEVEL_REG_MAX_DECIBELS)
        reg.set_value(0, value)


    @property
    def loud_threshold(self) -> Optional[float]:
        """
        The sound level to trigger a loud event., /
        """
        reg = self.register(JD_SOUND_LEVEL_REG_LOUD_THRESHOLD)
        value = reg.value(0)
        return cast(Optional[float], value)

    @loud_threshold.setter
    def loud_threshold(self, value: float) -> None:
        reg = self.register(JD_SOUND_LEVEL_REG_LOUD_THRESHOLD)
        reg.set_value(0, value)


    @property
    def quiet_threshold(self) -> Optional[float]:
        """
        The sound level to trigger a quiet event., /
        """
        reg = self.register(JD_SOUND_LEVEL_REG_QUIET_THRESHOLD)
        value = reg.value(0)
        return cast(Optional[float], value)

    @quiet_threshold.setter
    def quiet_threshold(self, value: float) -> None:
        reg = self.register(JD_SOUND_LEVEL_REG_QUIET_THRESHOLD)
        reg.set_value(0, value)


    def on_loud(self, handler: EventHandlerFn) -> UnsubscribeFn:
        """
        Raised when a loud sound is detected
        """
        return self.on_event(JD_SOUND_LEVEL_EV_LOUD, handler)

    def on_quiet(self, handler: EventHandlerFn) -> UnsubscribeFn:
        """
        Raised when a period of quietness is detected
        """
        return self.on_event(JD_SOUND_LEVEL_EV_QUIET, handler)

    
