# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class SpeechSynthesisClient(Client):
    """
    A speech synthesizer
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_SPEECH_SYNTHESIS, JD_SPEECH_SYNTHESIS_PACK_FORMATS, role)
    

    @property
    def enabled(self) -> Optional[bool]:
        """
        Determines if the speech engine is in a non-paused state.
        """
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_ENABLED)
        value = reg.value(0)
        return cast(Optional[bool], value)

    @enabled.setter
    def enabled(self, value: bool) -> None:
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_ENABLED)
        reg.set_value(0, value)


    @property
    def lang(self) -> Optional[str]:
        """
        (Optional) Language used for utterances as defined in https://www.ietf.org/rfc/bcp/bcp47.txt.
        """
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_LANG)
        value = reg.value(0)
        return cast(Optional[str], value)

    @lang.setter
    def lang(self, value: str) -> None:
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_LANG)
        reg.set_value(0, value)


    @property
    def volume(self) -> Optional[float]:
        """
        (Optional) Volume for utterances., /
        """
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_VOLUME)
        value = reg.value(0)
        return cast(Optional[float], value)

    @volume.setter
    def volume(self, value: float) -> None:
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_VOLUME)
        reg.set_value(0, value)


    @property
    def pitch(self) -> Optional[float]:
        """
        (Optional) Pitch for utterances
        """
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_PITCH)
        value = reg.value(0)
        return cast(Optional[float], value)

    @pitch.setter
    def pitch(self, value: float) -> None:
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_PITCH)
        reg.set_value(0, value)


    @property
    def rate(self) -> Optional[float]:
        """
        (Optional) Rate for utterances
        """
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_RATE)
        value = reg.value(0)
        return cast(Optional[float], value)

    @rate.setter
    def rate(self, value: float) -> None:
        reg = self.register(JD_SPEECH_SYNTHESIS_REG_RATE)
        reg.set_value(0, value)



    def speak(self, text: str) -> None:
        """
        Adds an utterance to the utterance queue; it will be spoken when any other utterances queued before it have been spoken.
        """
        self.send_cmd_packed(JD_SPEECH_SYNTHESIS_CMD_SPEAK, text)

    def cancel(self, ) -> None:
        """
        Cancels current utterance and all utterances from the utterance queue.
        """
        self.send_cmd_packed(JD_SPEECH_SYNTHESIS_CMD_CANCEL, )
    
