# Autogenerated constants for DeviceScript Debugger service
from enum import IntEnum
from jacdac.constants import *
from jacdac.system.constants import *
JD_SERVICE_CLASS_DEVS_DBG = const(0x155b5b40)


class DevsDbgValueTag(IntEnum):
    NUMBER = const(0x1)
    SPECIAL = const(0x2)
    FIBER = const(0x3)
    BUILTIN_OBJECT = const(0x5)
    EXOTIC = const(0x6)
    UNHANDLED = const(0x7)
    IMG_BUFFER = const(0x20)
    IMG_STRING_BUILTIN = const(0x21)
    IMG_STRING_ASCII = const(0x22)
    IMG_STRING_UTF8 = const(0x23)
    IMG_ROLE = const(0x30)
    IMG_FUNCTION = const(0x31)
    IMG_ROLE_MEMBER = const(0x32)
    OBJ_ARRAY = const(0x51)
    OBJ_MAP = const(0x52)
    OBJ_BUFFER = const(0x53)
    OBJ_STRING = const(0x54)
    OBJ_STACK_FRAME = const(0x55)
    OBJ_PACKET = const(0x56)
    OBJ_BOUND_FUNCTION = const(0x57)
    OBJ_OPAQUE = const(0x58)
    OBJ_ANY = const(0x50)
    OBJ_MASK = const(0xf0)
    USER1 = const(0xf1)
    USER2 = const(0xf2)
    USER3 = const(0xf3)
    USER4 = const(0xf4)


class DevsDbgValueSpecial(IntEnum):
    UNDEFINED = const(0x0)
    TRUE = const(0x1)
    FALSE = const(0x2)
    NULL = const(0x3)
    GLOBALS = const(0x64)
    CURRENT_EXCEPTION = const(0x65)


class DevsDbgFunIdx(IntEnum):
    NONE = const(0x0)
    MAIN = const(0xc34f)
    FIRST_BUILT_IN = const(0xc350)


class DevsDbgFiberHandle(IntEnum):
    NONE = const(0x0)


class DevsDbgProgramCounter(IntEnum):


class DevsDbgObjStackFrame(IntEnum):
    NULL = const(0x0)


class DevsDbgString(IntEnum):
    STATIC_INDICATOR_MASK = const(0x80000001)
    STATIC_TAG_MASK = const(0x7f000000)
    STATIC_INDEX_MASK = const(0xfffffe)
    UNHANDLED = const(0x0)


class DevsDbgStepFlags(IntEnum):
    STEP_OUT = const(0x1)
    STEP_IN = const(0x2)
    THROW = const(0x4)


class DevsDbgSuspensionType(IntEnum):
    NONE = const(0x0)
    BREAKPOINT = const(0x1)
    UNHANDLED_EXCEPTION = const(0x2)
    HANDLED_EXCEPTION = const(0x3)
    HALT = const(0x4)
    PANIC = const(0x5)
    RESTART = const(0x6)
    DEBUGGER_STMT = const(0x7)
    STEP = const(0x8)


JD_DEVS_DBG_CMD_READ_FIBERS = const(0x80)
JD_DEVS_DBG_CMD_READ_STACK = const(0x81)
JD_DEVS_DBG_CMD_READ_INDEXED_VALUES = const(0x82)
JD_DEVS_DBG_CMD_READ_NAMED_VALUES = const(0x83)
JD_DEVS_DBG_CMD_READ_VALUE = const(0x84)
JD_DEVS_DBG_CMD_READ_BYTES = const(0x85)
JD_DEVS_DBG_CMD_SET_BREAKPOINTS = const(0x90)
JD_DEVS_DBG_CMD_CLEAR_BREAKPOINTS = const(0x91)
JD_DEVS_DBG_CMD_CLEAR_ALL_BREAKPOINTS = const(0x92)
JD_DEVS_DBG_CMD_RESUME = const(0x93)
JD_DEVS_DBG_CMD_HALT = const(0x94)
JD_DEVS_DBG_CMD_RESTART_AND_HALT = const(0x95)
JD_DEVS_DBG_CMD_STEP = const(0x96)
JD_DEVS_DBG_REG_ENABLED = const(JD_REG_INTENSITY)
JD_DEVS_DBG_REG_BREAK_AT_UNHANDLED_EXN = const(0x80)
JD_DEVS_DBG_REG_BREAK_AT_HANDLED_EXN = const(0x81)
JD_DEVS_DBG_REG_IS_SUSPENDED = const(0x180)
JD_DEVS_DBG_EV_SUSPENDED = const(0x80)
JD_DEVS_DBG_PACK_FORMATS = {
    JD_DEVS_DBG_CMD_READ_FIBERS: "b[12]",
    JD_DEVS_DBG_CMD_READ_STACK: "b[12] u32",
    JD_DEVS_DBG_CMD_READ_INDEXED_VALUES: "b[12] u32 u8 u8 u16 u16",
    JD_DEVS_DBG_CMD_READ_NAMED_VALUES: "b[12] u32 u8",
    JD_DEVS_DBG_CMD_READ_VALUE: "u32 u8",
    JD_DEVS_DBG_CMD_READ_BYTES: "b[12] u32 u8 u8 u16 u16",
    JD_DEVS_DBG_CMD_SET_BREAKPOINTS: "r: u32",
    JD_DEVS_DBG_CMD_CLEAR_BREAKPOINTS: "r: u32",
    JD_DEVS_DBG_CMD_STEP: "u32 u16 u16 r: u32",
    JD_DEVS_DBG_REG_ENABLED: "u8",
    JD_DEVS_DBG_REG_BREAK_AT_UNHANDLED_EXN: "u8",
    JD_DEVS_DBG_REG_BREAK_AT_HANDLED_EXN: "u8",
    JD_DEVS_DBG_REG_IS_SUSPENDED: "u8",
    JD_DEVS_DBG_EV_SUSPENDED: "u32 u8"
}
