# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class PotentiometerClient(Client):
    """
    A slider or rotary potentiometer.
    Implements a client for the `Potentiometer <https://microsoft.github.io/jacdac-docs/services/potentiometer>`_ service.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_POTENTIOMETER, JD_POTENTIOMETER_PACK_FORMATS, role)
    

    @property
    def position(self) -> Optional[float]:
        """
        The relative position of the slider., _: /
        """
        reg = self.register(JD_POTENTIOMETER_REG_POSITION)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def variant(self) -> Optional[PotentiometerVariant]:
        """
        (Optional) Specifies the physical layout of the potentiometer., 
        """
        reg = self.register(JD_POTENTIOMETER_REG_VARIANT)
        values = reg.values()
        return cast(Optional[PotentiometerVariant], values[0] if values else None)

    
