# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client, EventHandlerFn, UnsubscribeFn
from .constants import *



class DeviceScriptConditionClient(Client):
    """
    Conditions are synthetic services used to synchronize threads of executions of a DeviceScript VM.
    Implements a client for the `DeviceScript Condition <https://microsoft.github.io/jacdac-docs/services/devicescriptcondition>`_ service.

    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_DEVICE_SCRIPT_CONDITION, JD_DEVICE_SCRIPT_CONDITION_PACK_FORMATS, role)


    def on_signalled(self, handler: EventHandlerFn) -> UnsubscribeFn:
        """
        Triggered by `signal` command.
        """
        return self.on_event(JD_DEVICE_SCRIPT_CONDITION_EV_SIGNALLED, handler)


    def signal(self, ) -> None:
        """
        Triggers a `signalled` event.
        """
        self.send_cmd_packed(JD_DEVICE_SCRIPT_CONDITION_CMD_SIGNAL, )
    
