# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *



class PCControllerClient(Client):
    """
    Send various events to PC, including opening a URL, start an app, sending text, etc.
    Implements a client for the `PC controller <https://microsoft.github.io/jacdac-docs/services/pccontroller>`_ service.

    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_PCCONTROLLER, JD_PCCONTROLLER_PACK_FORMATS, role)



    def open_url(self, url: str) -> None:
        """
        Open a URL in the default browser.
        """
        self.send_cmd_packed(JD_PCCONTROLLER_CMD_OPEN_URL, url)

    def start_app(self, name: str) -> None:
        """
        Start an app.
        """
        self.send_cmd_packed(JD_PCCONTROLLER_CMD_START_APP, name)

    def send_text(self, text: str) -> None:
        """
        Send text to the active window.
        """
        self.send_cmd_packed(JD_PCCONTROLLER_CMD_SEND_TEXT, text)

    def run_script(self, script: str) -> None:
        """
        Run a script.
        """
        self.send_cmd_packed(JD_PCCONTROLLER_CMD_RUN_SCRIPT, script)
    
