# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class VibrationMotorClient(Client):
    """
    A vibration motor.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_VIBRATION_MOTOR, JD_VIBRATION_MOTOR_PACK_FORMATS, role)
    

    @property
    def enabled(self) -> Optional[bool]:
        """
        Determines if the vibration motor responds to vibrate commands.
        """
        reg = self.register(JD_VIBRATION_MOTOR_REG_ENABLED)
        value = reg.value(0)
        return cast(Optional[bool], value)

    @enabled.setter
    def enabled(self, value: bool) -> None:
        reg = self.register(JD_VIBRATION_MOTOR_REG_ENABLED)
        reg.set_value(0, value)


    
