# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class RainGaugeClient(Client):
    """
    Measures the amount of liquid precipitation over an area in a predefined period of time.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_RAIN_GAUGE, JD_RAIN_GAUGE_PACK_FORMATS, role)
    

    @property
    def precipitation(self) -> Optional[float]:
        """
        Total precipitation recorded so far., _: mm
        """
        reg = self.register(JD_RAIN_GAUGE_REG_PRECIPITATION)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def precipitation_precision(self) -> Optional[float]:
        """
        (Optional) Typically the amount of rain needed for tipping the bucket., _: mm
        """
        reg = self.register(JD_RAIN_GAUGE_REG_PRECIPITATION_PRECISION)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    
