# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast
from jacdac.events import EventHandlerFn, UnsubscribeFn

class RelayClient(Client):
    """
    A switching relay.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_RELAY, JD_RELAY_PACK_FORMATS, role)
    

    @property
    def closed(self) -> Optional[bool]:
        """
        Indicates whether the relay circuit is currently energized (closed) or not., 
        """
        reg = self.register(JD_RELAY_REG_CLOSED)
        values = reg.values()
        return cast(Optional[bool], values[0] if values else None)

    @closed.setter
    def closed(self, value: bool) -> None:
        reg = self.register(JD_RELAY_REG_CLOSED)
        reg.set_values(value) # type: ignore


    @property
    def variant(self) -> Optional[RelayVariant]:
        """
        (Optional) Describes the type of relay used., 
        """
        reg = self.register(JD_RELAY_REG_VARIANT)
        values = reg.values()
        return cast(Optional[RelayVariant], values[0] if values else None)

    @property
    def max_switching_current(self) -> Optional[int]:
        """
        (Optional) Maximum switching current for a resistive load., _: mA
        """
        reg = self.register(JD_RELAY_REG_MAX_SWITCHING_CURRENT)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    def on_active(self, handler: EventHandlerFn) -> UnsubscribeFn:
        """
        Emitted when relay goes from `inactive` to `active` state.
        Normally open (NO) relays close the circuit when activated.
        """
        return self.on_event(JD_RELAY_EV_ACTIVE, handler)

    def on_inactive(self, handler: EventHandlerFn) -> UnsubscribeFn:
        """
        Emitted when relay goes from `active` to `inactive` state.
        Normally closed (NC) relays open the circuit when activated.
        """
        return self.on_event(JD_RELAY_EV_INACTIVE, handler)

    
