# Autogenerated constants for Barometer service
from jacdac.constants import *
from jacdac.system.constants import *
JD_SERVICE_CLASS_BAROMETER = const(0x1e117cea)
JD_BAROMETER_REG_PRESSURE = const(JD_REG_READING)
JD_BAROMETER_REG_PRESSURE_ERROR = const(JD_REG_READING_ERROR)
JD_BAROMETER_PACK_FORMATS = {
    JD_BAROMETER_REG_PRESSURE: "u22.10",
    JD_BAROMETER_REG_PRESSURE_ERROR: "u22.10"
}
