# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *



class DashboardClient(Client):
    """
    Device that interacts, configure or inspects with the services on the bus. While a dashboard is on the bus, heuristics like device reset should be disabled.
    Implements a client for the `Dashboard <https://microsoft.github.io/jacdac-docs/services/dashboard>`_ service.

    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_DASHBOARD, JD_DASHBOARD_PACK_FORMATS, role)


    
