# Autogenerated constants for I2C service
from enum import IntEnum
from jacdac.constants import *
JD_SERVICE_CLASS_I2C = const(0x1c18ca43)


class I2CStatus(IntEnum):
    OK = const(0x0)
    NACK_ADDR = const(0x1)
    NACK_DATA = const(0x2)
    NO_I2C = const(0x3)


JD_I2C_REG_OK = const(0x180)
JD_I2C_CMD_TRANSACTION = const(0x80)
JD_I2C_PACK_FORMATS = {
    JD_I2C_REG_OK: "u8",
    JD_I2C_CMD_TRANSACTION: "u8 u8 b"
}
