# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class BitRadioClient(Client):
    """
    Support for sending and receiving packets using the [Bit Radio protocol](https://github.com/microsoft/pxt-common-packages/blob/master/libs/radio/docs/reference/radio.md), typically used between micro:bit devices.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_BIT_RADIO, JD_BIT_RADIO_PACK_FORMATS, role)
    

    @property
    def enabled(self) -> Optional[bool]:
        """
        Turns on/off the radio antenna., 
        """
        reg = self.register(JD_BIT_RADIO_REG_ENABLED)
        values = reg.values()
        return cast(Optional[bool], values[0] if values else None)

    @enabled.setter
    def enabled(self, value: bool) -> None:
        reg = self.register(JD_BIT_RADIO_REG_ENABLED)
        reg.set_values(value) # type: ignore


    @property
    def group(self) -> Optional[int]:
        """
        Group used to filter packets, 
        """
        reg = self.register(JD_BIT_RADIO_REG_GROUP)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    @group.setter
    def group(self, value: int) -> None:
        reg = self.register(JD_BIT_RADIO_REG_GROUP)
        reg.set_values(value) # type: ignore


    @property
    def transmission_power(self) -> Optional[int]:
        """
        Antenna power to increase or decrease range., 
        """
        reg = self.register(JD_BIT_RADIO_REG_TRANSMISSION_POWER)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    @transmission_power.setter
    def transmission_power(self, value: int) -> None:
        reg = self.register(JD_BIT_RADIO_REG_TRANSMISSION_POWER)
        reg.set_values(value) # type: ignore


    @property
    def frequency_band(self) -> Optional[int]:
        """
        Change the transmission and reception band of the radio to the given channel., 
        """
        reg = self.register(JD_BIT_RADIO_REG_FREQUENCY_BAND)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    @frequency_band.setter
    def frequency_band(self, value: int) -> None:
        reg = self.register(JD_BIT_RADIO_REG_FREQUENCY_BAND)
        reg.set_values(value) # type: ignore



    def send_string(self, message: str) -> None:
        """
        Sends a string payload as a radio message, maximum 18 characters.
        """
        self.send_cmd_packed(JD_BIT_RADIO_CMD_SEND_STRING, message)

    def send_number(self, value: float) -> None:
        """
        Sends a double precision number payload as a radio message
        """
        self.send_cmd_packed(JD_BIT_RADIO_CMD_SEND_NUMBER, value)

    def send_value(self, value: float, name: str) -> None:
        """
        Sends a double precision number and a name payload as a radio message
        """
        self.send_cmd_packed(JD_BIT_RADIO_CMD_SEND_VALUE, value, name)

    def send_buffer(self, data: bytes) -> None:
        """
        Sends a payload of bytes as a radio message
        """
        self.send_cmd_packed(JD_BIT_RADIO_CMD_SEND_BUFFER, data)
    
