# Autogenerated constants for USB Bridge service
from enum import IntEnum
from jacdac.constants import *
JD_SERVICE_CLASS_USB_BRIDGE = const(0x18f61a4a)


class UsbBridgeQByte(IntEnum):
    MAGIC = const(0xfe)
    LITERAL_MAGIC = const(0xf8)
    RESERVED = const(0xf9)
    SERIAL_GAP = const(0xfa)
    FRAME_GAP = const(0xfb)
    FRAME_START = const(0xfc)
    FRAME_END = const(0xfd)


JD_USB_BRIDGE_CMD_DISABLE_PACKETS = const(0x80)
JD_USB_BRIDGE_CMD_ENABLE_PACKETS = const(0x81)
JD_USB_BRIDGE_CMD_DISABLE_LOG = const(0x82)
JD_USB_BRIDGE_CMD_ENABLE_LOG = const(0x83)
JD_USB_BRIDGE_PACK_FORMATS = {

}
