# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class HeartRateClient(Client):
    """
    A sensor approximating the heart rate. 
     * 
     * 
     * **Jacdac is NOT suitable for medical devices and should NOT be used in any kind of device to diagnose or treat any medical conditions.**
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_HEART_RATE, JD_HEART_RATE_PACK_FORMATS, role)
    

    @property
    def heart_rate(self) -> Optional[float]:
        """
        The estimated heart rate., bpm
        """
        reg = self.register(JD_HEART_RATE_REG_HEART_RATE)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def heart_rate_error(self) -> Optional[float]:
        """
        (Optional) The estimated error on the reported sensor data., bpm
        """
        reg = self.register(JD_HEART_RATE_REG_HEART_RATE_ERROR)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def variant(self) -> Optional[HeartRateVariant]:
        """
        (Optional) The type of physical sensor
        """
        reg = self.register(JD_HEART_RATE_REG_VARIANT)
        value = reg.value(0)
        return cast(Optional[HeartRateVariant], value)

    
