# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class HeartRateClient(Client):
    """
    A sensor approximating the heart rate. 
     * 
     * 
     * **Jacdac is NOT suitable for medical devices and should NOT be used in any kind of device to diagnose or treat any medical conditions.**
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_HEART_RATE, JD_HEART_RATE_PACK_FORMATS, role)
    

    @property
    def heart_rate(self) -> Optional[float]:
        """
        The estimated heart rate., _: bpm
        """
        reg = self.register(JD_HEART_RATE_REG_HEART_RATE)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def heart_rate_error(self) -> Optional[float]:
        """
        (Optional) The estimated error on the reported sensor data., _: bpm
        """
        reg = self.register(JD_HEART_RATE_REG_HEART_RATE_ERROR)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def variant(self) -> Optional[HeartRateVariant]:
        """
        (Optional) The type of physical sensor, 
        """
        reg = self.register(JD_HEART_RATE_REG_VARIANT)
        values = reg.values()
        return cast(Optional[HeartRateVariant], values[0] if values else None)

    
