# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class SolenoidClient(Client):
    """
    A push-pull solenoid is a type of relay that pulls a coil when activated.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_SOLENOID, JD_SOLENOID_PACK_FORMATS, role)
    

    @property
    def pulled(self) -> Optional[bool]:
        """
        Indicates whether the solenoid is energized and pulled (on) or pushed (off)., 
        """
        reg = self.register(JD_SOLENOID_REG_PULLED)
        values = reg.values()
        return cast(Optional[bool], values[0] if values else None)

    @pulled.setter
    def pulled(self, value: bool) -> None:
        reg = self.register(JD_SOLENOID_REG_PULLED)
        reg.set_values(value) # type: ignore


    @property
    def variant(self) -> Optional[SolenoidVariant]:
        """
        (Optional) Describes the type of solenoid used., 
        """
        reg = self.register(JD_SOLENOID_REG_VARIANT)
        values = reg.values()
        return cast(Optional[SolenoidVariant], values[0] if values else None)

    
