# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class SolenoidClient(Client):
    """
    A push-pull solenoid is a type of relay that pulls a coil when activated.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_SOLENOID, JD_SOLENOID_PACK_FORMATS, role)
    

    @property
    def pulled(self) -> Optional[bool]:
        """
        Indicates whether the solenoid is energized and pulled (on) or pushed (off).
        """
        reg = self.register(JD_SOLENOID_REG_PULLED)
        value = reg.value(0)
        return cast(Optional[bool], value)

    @pulled.setter
    def pulled(self, value: bool) -> None:
        reg = self.register(JD_SOLENOID_REG_PULLED)
        reg.set_value(0, value)


    @property
    def variant(self) -> Optional[SolenoidVariant]:
        """
        (Optional) Describes the type of solenoid used.
        """
        reg = self.register(JD_SOLENOID_REG_VARIANT)
        value = reg.value(0)
        return cast(Optional[SolenoidVariant], value)

    
