# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class TrafficLightClient(Client):
    """
    Controls a mini traffic with a red, orange and green LED.
    Implements a client for the `Traffic Light <https://microsoft.github.io/jacdac-docs/services/trafficlight>`_ service.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_TRAFFIC_LIGHT, JD_TRAFFIC_LIGHT_PACK_FORMATS, role)
    

    @property
    def red(self) -> Optional[bool]:
        """
        The on/off state of the red light., 
        """
        reg = self.register(JD_TRAFFIC_LIGHT_REG_RED)
        values = reg.values()
        return cast(Optional[bool], values[0] if values else None)

    @red.setter
    def red(self, value: bool) -> None:
        reg = self.register(JD_TRAFFIC_LIGHT_REG_RED)
        reg.set_values(value)


    @property
    def orange(self) -> Optional[bool]:
        """
        The on/off state of the red light., 
        """
        reg = self.register(JD_TRAFFIC_LIGHT_REG_ORANGE)
        values = reg.values()
        return cast(Optional[bool], values[0] if values else None)

    @orange.setter
    def orange(self, value: bool) -> None:
        reg = self.register(JD_TRAFFIC_LIGHT_REG_ORANGE)
        reg.set_values(value)


    @property
    def green(self) -> Optional[bool]:
        """
        The on/off state of the red light., 
        """
        reg = self.register(JD_TRAFFIC_LIGHT_REG_GREEN)
        values = reg.values()
        return cast(Optional[bool], values[0] if values else None)

    @green.setter
    def green(self, value: bool) -> None:
        reg = self.register(JD_TRAFFIC_LIGHT_REG_GREEN)
        reg.set_values(value)


    
