# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class ECO2Client(Client):
    """
    Measures equivalent CO₂ levels.
    Implements a client for the `Equivalent CO₂ <https://microsoft.github.io/jacdac-docs/services/eco2>`_ service.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_E_CO2, JD_E_CO2_PACK_FORMATS, role)
    

    @property
    def e_CO2(self) -> Optional[float]:
        """
        Equivalent CO₂ (eCO₂) readings., _: ppm
        """
        reg = self.register(JD_E_CO2_REG_E_CO2)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def e_CO2_error(self) -> Optional[float]:
        """
        Error on the reading value., _: ppm
        """
        reg = self.register(JD_E_CO2_REG_E_CO2_ERROR)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def min_e_CO2(self) -> Optional[float]:
        """
        (Optional) Minimum measurable value, _: ppm
        """
        reg = self.register(JD_E_CO2_REG_MIN_E_CO2)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def max_e_CO2(self) -> Optional[float]:
        """
        (Optional) Minimum measurable value, _: ppm
        """
        reg = self.register(JD_E_CO2_REG_MAX_E_CO2)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def conditioning_period(self) -> Optional[int]:
        """
        (Optional) Time required to achieve good sensor stability before measuring after long idle period., _: s
        """
        reg = self.register(JD_E_CO2_REG_CONDITIONING_PERIOD)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    @property
    def variant(self) -> Optional[ECO2Variant]:
        """
        (Optional) Type of physical sensor and capabilities., 
        """
        reg = self.register(JD_E_CO2_REG_VARIANT)
        values = reg.values()
        return cast(Optional[ECO2Variant], values[0] if values else None)

    
