# Autogenerated constants for GPIO service
from enum import IntEnum
from jacdac.constants import *
from jacdac.system.constants import *
JD_SERVICE_CLASS_GPIO = const(0x10d85a69)


class GPIOMode(IntEnum):
    OFF = const(0x0)
    OFF_PULL_UP = const(0x10)
    OFF_PULL_DOWN = const(0x20)
    INPUT = const(0x1)
    INPUT_PULL_UP = const(0x11)
    INPUT_PULL_DOWN = const(0x21)
    OUTPUT = const(0x2)
    OUTPUT_HIGH = const(0x12)
    OUTPUT_LOW = const(0x22)
    ANALOG_IN = const(0x3)
    ALTERNATIVE = const(0x4)
    BASE_MODE_MASK = const(0xf)


class GPIOCapabilities(IntEnum):
    PULL_UP = const(0x1)
    PULL_DOWN = const(0x2)
    INPUT = const(0x4)
    OUTPUT = const(0x8)
    ANALOG = const(0x10)


JD_GPIO_REG_STATE = const(JD_REG_READING)
JD_GPIO_REG_NUM_PINS = const(0x180)
JD_GPIO_CMD_CONFIGURE = const(0x80)
JD_GPIO_CMD_PIN_INFO = const(0x81)
JD_GPIO_CMD_PIN_BY_LABEL = const(0x83)
JD_GPIO_CMD_PIN_BY_HW_PIN = const(0x84)
JD_GPIO_PACK_FORMATS = {
    JD_GPIO_REG_STATE: "b",
    JD_GPIO_REG_NUM_PINS: "u8",
    JD_GPIO_CMD_CONFIGURE: "r: u8 u8",
    JD_GPIO_CMD_PIN_INFO: "u8",
    JD_GPIO_CMD_PIN_BY_LABEL: "s",
    JD_GPIO_CMD_PIN_BY_HW_PIN: "u8"
}
