# Autogenerated constants for Base service service
from jacdac.constants import *
from jacdac.system.constants import *
JD_PACK_FORMATS = {
    JD_CMD_COMMAND_NOT_IMPLEMENTED: "u16 u16",
    JD_REG_INSTANCE_NAME: "s",
    JD_REG_STATUS_CODE: "u16 u16",
    JD_EV_STATUS_CODE_CHANGED: "u16 u16"
}
