# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class ColorClient(Client):
    """
    Senses RGB colors
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_COLOR, JD_COLOR_PACK_FORMATS, role)
    

    @property
    def color(self) -> Optional[tuple[float, float, float]]:
        """
        Detected color in the RGB color space., red: /,green: /,blue: /
        """
        reg = self.register(JD_COLOR_REG_COLOR)
        values = reg.values()
        return cast(Optional[tuple[float, float, float]], values)

    
