# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class ColorClient(Client):
    """
    Senses RGB colors
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_COLOR, JD_COLOR_PACK_FORMATS, role)
    

    @property
    def red(self) -> Optional[float]:
        """
        Detected color in the RGB color space., /
        """
        reg = self.register(JD_COLOR_REG_COLOR)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def green(self) -> Optional[float]:
        """
        Detected color in the RGB color space., /
        """
        reg = self.register(JD_COLOR_REG_COLOR)
        value = reg.value(1)
        return cast(Optional[float], value)

    @property
    def blue(self) -> Optional[float]:
        """
        Detected color in the RGB color space., /
        """
        reg = self.register(JD_COLOR_REG_COLOR)
        value = reg.value(2)
        return cast(Optional[float], value)

    
