# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class WeightScaleClient(Client):
    """
    A weight measuring sensor.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_WEIGHT_SCALE, JD_WEIGHT_SCALE_PACK_FORMATS, role)
    

    @property
    def weight(self) -> Optional[float]:
        """
        The reported weight., _: kg
        """
        reg = self.register(JD_WEIGHT_SCALE_REG_WEIGHT)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def weight_error(self) -> Optional[float]:
        """
        (Optional) The estimate error on the reported reading., _: kg
        """
        reg = self.register(JD_WEIGHT_SCALE_REG_WEIGHT_ERROR)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def zero_offset(self) -> Optional[float]:
        """
        (Optional) Calibrated zero offset error on the scale, i.e. the measured weight when nothing is on the scale.
        You do not need to subtract that from the reading, it has already been done., _: kg
        """
        reg = self.register(JD_WEIGHT_SCALE_REG_ZERO_OFFSET)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @zero_offset.setter
    def zero_offset(self, value: float) -> None:
        reg = self.register(JD_WEIGHT_SCALE_REG_ZERO_OFFSET)
        reg.set_values(value) # type: ignore


    @property
    def gain(self) -> Optional[float]:
        """
        (Optional) Calibrated gain on the weight scale error., 
        """
        reg = self.register(JD_WEIGHT_SCALE_REG_GAIN)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @gain.setter
    def gain(self, value: float) -> None:
        reg = self.register(JD_WEIGHT_SCALE_REG_GAIN)
        reg.set_values(value) # type: ignore


    @property
    def max_weight(self) -> Optional[float]:
        """
        (Optional) Maximum supported weight on the scale., _: kg
        """
        reg = self.register(JD_WEIGHT_SCALE_REG_MAX_WEIGHT)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def min_weight(self) -> Optional[float]:
        """
        (Optional) Minimum recommend weight on the scale., _: kg
        """
        reg = self.register(JD_WEIGHT_SCALE_REG_MIN_WEIGHT)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def weight_resolution(self) -> Optional[float]:
        """
        (Optional) Smallest, yet distinguishable change in reading., _: kg
        """
        reg = self.register(JD_WEIGHT_SCALE_REG_WEIGHT_RESOLUTION)
        values = reg.values()
        return cast(Optional[float], values[0] if values else None)

    @property
    def variant(self) -> Optional[WeightScaleVariant]:
        """
        (Optional) The type of physical scale, 
        """
        reg = self.register(JD_WEIGHT_SCALE_REG_VARIANT)
        values = reg.values()
        return cast(Optional[WeightScaleVariant], values[0] if values else None)


    def calibrate_zero_offset(self, ) -> None:
        """
        Call this command when there is nothing on the scale. If supported, the module should save the calibration data.
        """
        self.send_cmd_packed(JD_WEIGHT_SCALE_CMD_CALIBRATE_ZERO_OFFSET, )

    def calibrate_gain(self, weight: float) -> None:
        """
        Call this command with the weight of the thing on the scale.
        """
        self.send_cmd_packed(JD_WEIGHT_SCALE_CMD_CALIBRATE_GAIN, weight)
    
