# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class SensorAggregatorClient(Client):
    """
    Aggregate data from multiple sensors into a single stream
     * (often used as input to machine learning models on the same device, see model runner service).
    Implements a client for the `Sensor Aggregator <https://microsoft.github.io/jacdac-docs/services/sensoraggregator>`_ service.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_SENSOR_AGGREGATOR, JD_SENSOR_AGGREGATOR_PACK_FORMATS, role)
    

    @property
    def num_samples(self) -> Optional[int]:
        """
        Number of input samples collected so far., 
        """
        reg = self.register(JD_SENSOR_AGGREGATOR_REG_NUM_SAMPLES)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    @property
    def sample_size(self) -> Optional[int]:
        """
        Size of a single sample., _: B
        """
        reg = self.register(JD_SENSOR_AGGREGATOR_REG_SAMPLE_SIZE)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    @property
    def streaming_samples(self) -> Optional[int]:
        """
        When set to `N`, will stream `N` samples as `current_sample` reading., _: #
        """
        reg = self.register(JD_SENSOR_AGGREGATOR_REG_STREAMING_SAMPLES)
        values = reg.values()
        return cast(Optional[int], values[0] if values else None)

    @streaming_samples.setter
    def streaming_samples(self, value: int) -> None:
        reg = self.register(JD_SENSOR_AGGREGATOR_REG_STREAMING_SAMPLES)
        reg.set_values(value)


    @property
    def current_sample(self) -> Optional[bytes]:
        """
        Last collected sample., 
        """
        reg = self.register(JD_SENSOR_AGGREGATOR_REG_CURRENT_SAMPLE)
        values = reg.values()
        return cast(Optional[bytes], values[0] if values else None)

    
