# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class UvIndexClient(Client):
    """
    The UV Index is a measure of the intensity of ultraviolet (UV) rays from the Sun.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_UV_INDEX, JD_UV_INDEX_PACK_FORMATS, role)
    

    @property
    def uv_index(self) -> Optional[float]:
        """
        Ultraviolet index, typically refreshed every second., uv
        """
        reg = self.register(JD_UV_INDEX_REG_UV_INDEX)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def uv_index_error(self) -> Optional[float]:
        """
        (Optional) Error on the UV measure., uv
        """
        reg = self.register(JD_UV_INDEX_REG_UV_INDEX_ERROR)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def variant(self) -> Optional[UvIndexVariant]:
        """
        (Optional) The type of physical sensor and capabilities.
        """
        reg = self.register(JD_UV_INDEX_REG_VARIANT)
        value = reg.value(0)
        return cast(Optional[UvIndexVariant], value)

    
