# Autogenerated file. Do not edit.
from jacdac.bus import Bus, Client
from .constants import *
from typing import Optional, cast


class HumidityClient(Client):
    """
    A sensor measuring humidity of outside environment.
    """

    def __init__(self, bus: Bus, role: str) -> None:
        super().__init__(bus, JD_SERVICE_CLASS_HUMIDITY, JD_HUMIDITY_PACK_FORMATS, role)
    

    @property
    def humidity(self) -> Optional[float]:
        """
        The relative humidity in percentage of full water saturation., %RH
        """
        reg = self.register(JD_HUMIDITY_REG_HUMIDITY)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def humidity_error(self) -> Optional[float]:
        """
        The real humidity is between `humidity - humidity_error` and `humidity + humidity_error`., %RH
        """
        reg = self.register(JD_HUMIDITY_REG_HUMIDITY_ERROR)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def min_humidity(self) -> Optional[float]:
        """
        Lowest humidity that can be reported., %RH
        """
        reg = self.register(JD_HUMIDITY_REG_MIN_HUMIDITY)
        value = reg.value(0)
        return cast(Optional[float], value)

    @property
    def max_humidity(self) -> Optional[float]:
        """
        Highest humidity that can be reported., %RH
        """
        reg = self.register(JD_HUMIDITY_REG_MAX_HUMIDITY)
        value = reg.value(0)
        return cast(Optional[float], value)

    
